version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile 
    # 変更を保存するファイルを指定
    volumes:
      - .:/DIY_log
    # ポートを指定
    ports:
      - "3000:3000"
    # コンテナの起動を維持させる
    tty: true
    stdin_open: true

